### ISSUE TITLE
Question: could this UI approach work with Blazor too?

### ISSUE THREAD

**Issue by sandervandevelde** [Azure-Samples/iot-edge-hmi-module#3]
Hello,

I am trying to get a Blazor (server-side) app running as a Docker container too.

I am able to get the app deployed to an IoT Edge device but the integration with routing fails.

(below changes are added to a vanilla Blazor app).

I added this singleton class with the IoT Edge stuff:

```
using System;
using System.Text;
using System.Threading.Tasks;

using Microsoft.Azure.Devices.Client;
using Microsoft.Azure.Devices.Client.Transport.Mqtt;
using Newtonsoft.Json;

namespace BlazorEdgeModule.Edge
{
    public class IoTEdgeService
    {
        private ModuleClient ioTHubModuleClient;

        private int counter = int.MinValue;

        public IoTEdgeService()
        {
            Console.WriteLine("Starting IoTEdgeService singleton");

            Init().Wait();
        }

        private async Task Init()
        {
            MqttTransportSettings mqttSetting = new MqttTransportSettings(TransportType.Mqtt_Tcp_Only);
            ITransportSettings[] settings = { mqttSetting };

            Console.WriteLine("Create IoTEdgeService...");

            // Open a connection to the Edge runtime
            ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);

            Console.WriteLine("Open IoTEdgeService...");

            await ioTHubModuleClient.OpenAsync();

            Console.WriteLine("IoTEdgeService intialized.");
        }

        public async Task SendMessage()
        {
            Console.WriteLine("Sending Message");

            counter++;

            var messageBody = new MessageBody
            {
                counter = counter,
                timeStamp = DateTime.UtcNow,
            };

            var json = JsonConvert.SerializeObject(messageBody);

            using (var message = new Message(Encoding.UTF8.GetBytes(json)))
            {
                await ioTHubModuleClient.SendEventAsync("output1", message);

                Console.WriteLine("Message sent");
            }
        }
    }

    public class MessageBody
    {
        public int counter { get; set; }

        public DateTime timeStamp { get; set; }
    }
}
```

and I added it to the startup.cs (in 'public void ConfigureServices(IServiceCollection services)'):

```
services.AddSingleton<IoTEdgeService>();
```

but when the singleton is referenced:

```
@using BlazorEdgeModule.Edge
@inject IoTEdgeService EdgeService

...

<button class="btn btn-primary" @onclick="Send">Send message</button>

....

@code {
    private async Task Send()
    {
        await EdgeService.SendMessage();
    }
}
```

... the ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings); seems to create an infinite wait...

I also tried to add a new user, just like the IoT Edge C# template in the 'dockerfile':

```
RUN useradd -ms /bin/bash moduleuser
USER moduleuser
```

... but this makes my container go crashing.

Do you have a clue what's causing the 'lock' when creating the IoT edge client?

**Comment by angellmethod** [comment]
Hi Sander - could you share the sample you're working on? I think there are several possibilities that could be causing the issue that I want to check.

**Comment by paloukari** [comment]
@sandervandevelde a couple of recommendations:
1. Use [this](https://havedatawilltrain.com/the-reasonable-man/) approach to abstract the SDKs `ModuleClient` and compose a module with Blazor's dependency injection
2. Then, use [this](https://havedatawilltrain.com/lysis/) approach to debug the Blazor app outside the container to see what's happening. 

One thing to check is if there's a conflict with the ports used in IoT Edge and Blazor

**Comment by sandervandevelde** [comment]
Hi gents, thanks for looking into this. 
The repo is available here: https://github.com/sandervandevelde/iot-edge-blazor 
@paloukari I will check your links now

**Comment by sandervandevelde** [comment]
Found the issue :-)
After having a coffee, I double-checked the code.

Handling the await in the constructor is the problem. 

The *right* way is:
```
        public IoTEdgeService()
        {
            Console.WriteLine("Starting IoTEdgeService singleton");

            Task.Run(() => this.Init()).Wait();
        }
```
